[build]
withGlobalTauri = false
distDir = "frontend/dist"
beforeDevCommand = "pnpm dev"
beforeBuildCommand = "pnpm build"
devPath = "http://localhost:1420"

[package]
productName = "Commit"

[tauri]
security = {}
macOSPrivateApi = true

[[tauri.windows]]
width = 800
height = 240
focus = false
visible = false
title = "Commit"
resizable = false
alwaysOnTop = true
fullscreen = false
transparent = true
hiddenTitle = true
skipTaskbar = true
decorations = false

[tauri.allowlist]
all = false
window = { startDragging = true }

[tauri.system-tray]
iconAsTemplate = true
menuOnLeftClick = false
iconPath = "icons/menubar.png"

[tauri.bundle]
active = true
targets = ["app", "dmg"]
category = "DeveloperTool"
macOS = { license = "LICENSE" }
identifier = "build.miguel.commit"
copyright = "Copyright Â© 2023 Miguel Piedrafita"
icon = [
    "icons/32x32.png",
    "icons/128x128.png",
    "icons/128x128@2x.png",
    "icons/icon.icns",
    "icons/icon.ico",
]

[tauri.updater]
active = true
endpoint = "https://github.com/m1guelpf/commit/releases/latest/download/latest.json"
pubkey = "dW50cnVzdGVkIGNvbW1lbnQ6IG1pbmlzaWduIHB1YmxpYyBrZXk6IDNENDk3QkZBQUZBNEZGRTMKUldUai82U3YrbnRKUFJtcEZQTGJRMFQ2K3VwYi9NL004NTVrTmhYbHRIWmsrTWFuaUVMOUIxMXoK"
